project:
  type: website
  output-dir: docs

website:
  navbar:
    title: Shriya Ejanthker
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: https://acrobat.adobe.com/link/review?uri=urn:aaid:scds:US:cf4c750d-961f-3a7b-bb0b-0d537d983da8
        text: Resume

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    



