project:
  type: website
  output-dir: docs

website:
  title: "Shriya Ejanthker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true
    



